# Generated by Django 5.2.1 on 2025-06-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_advertisment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisment',
        ),
    ]
