# Generated by Django 5.2.1 on 2025-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_delete_advertisment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='advertisments/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
